### ISSUE TITLE
Feature-Request: Gulp Plugin

### ISSUE THREAD

**Issue by HansUXdev** [micmro/Stylify-Me#11]
Hi awesome work!

I've been using [Zurb's style-sherpa](https://github.com/zurb/style-sherpa) with gulp and but I've looking into automating the process and then I found your site.

I was wondering if you'd ever consider making this into a gulp plugin?

**Comment by micmro** [comment]
Thanks. That's a cool idea. It should be doable, but I don't have a lot of time these days (and if so spend it with some newer projects) so I probably won't come around for this any time soon. This said PRs and partner projects are always welcome ;) and I'm more than happy to support someone working on this.

**Comment by HansUXdev** [comment]
Hey thanks for the reply. I know the feeling about being busy. I'm not too experienced with phantom or making to gulp plugin myself but I have been looking into it. If you have any useful learning resources let me know.

Broadly speaking, I was considering breaking down stylify-crawler.js into smaller modules to be more maintainable and extendable. So for example one file that gets colors. Another for fonts (styles, sizes, etc). Another that grabs the images. Then a module to put that information into markdown format. That way it can be used with other plugins like [Style-Sherpa](https://github.com/zurb/style-sherpa).

As for the plugin structure, I was thinking something like this:
```
var stylify = require('gulp-stylify');

.pipe(stylify({
  url: 'http://stylifyme.com/',
  options: {
       // uses gulp-sitemap to crawl the whole site, then repeat foreach page
      sitemap: true,

      // default is all but optionally you should be able to grab only images, colors, font
      type: all,

     // Output type can be html or md 
     out: html,
  }
  // 
  output: './dist/output.html'
}))
```

**Comment by micmro** [comment]
Cool, looks like a good start @HansUXdev! 

Regarding gulp plugins, I've written a few for work, but only followed gulps docs and looked at some existing ones as reference:
https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md
So sorry no good recommendations for that.

Not sure if it helps but you might be able to use [gulp-phantom](https://www.npmjs.com/package/gulp-phantom) to simplify the work with phantom (though it looks like it's not phantom 2 - the latest version).

Good luck and feel free to buzz me if you have any questions/problems.

**Comment by HansUXdev** [comment]
@micmro yeah I was looking into gulp-phantom, gulp-nightwatch-headless and cheerio (to replace jQuery and maybe improve speed). Right now, I'm just testing the options with console log on my spare/break-time.
