### ISSUE TITLE
TypeError: Cannot Read Property 'kill' of Undefined when trying to run it not-locally

### ISSUE THREAD

**Issue by jordan-cbw** [micmro/Stylify-Me#14]
Hello,

I created a local version of the app and it worked great. I then added it to my domain. I updated my valid refs for the new domain, but I was getting an invalid referer error. It kept trying to use http://stylify.herokuapp.com as the referer. I noticed that it's probably doing it because of this line. 

`app.get('/query', function(req, res){`
`              var referer = req.get("Referer")||"http://stylify.herokuapp.com"
                ,jsonResponse = {}
                ,showImage = true
                ,debugMode = false
                ,url, childArgs, phantomProcess;`

on line 197 of app.js

I changed the default referer to be "http://cssstyle.coolblueweb.net:4321/" (my domain). When I then go to "http://cssstyle.coolblueweb.net:4321/query?url=http%3A%2F%2Fgoogle.com", I get the 500 error. 
When I change the default referer address to be the one I'm sending from, I'm then getting a 500 error saying "TypeError: Cannot Read Property 'kill' of Undefined"

**Comment by micmro** [comment]
Sorry for the late reply. 

Looks like this migth have to do with this line:
https://github.com/micmro/Stylify-Me/blob/70cf5bf1992d2f6f2c1d1caa7a2bc1f26b55b10d/app.js#L217

So your setup can't create a phantomJs instance in this code block:
https://github.com/micmro/Stylify-Me/blob/70cf5bf1992d2f6f2c1d1caa7a2bc1f26b55b10d/app.js#L208-L214
