### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by solinyc** [micmro/Stylify-Me#28]
<img width="1110" alt="Screenshot 2023-01-08 at 12 22 33 PM" src="https://user-images.githubusercontent.com/72266712/211209985-e26e2b94-6ce0-4c2e-b6ef-2a4b32b7be5e.png">
Im getting an error that says "Could not query site, our service might be down, please try again later." no matter which website I try using.

**Comment by micmro** [comment]
Heroku has stopped it's free tier that Stylify Me API was using a few weeks ago and I didn't have time to move it over to another cloud service yet.
It might take a bit longer as I'm quite busy these days.

**Comment by solinyc** [comment]
Thank you for your response and your work!

**Comment by micmro** [comment]
Hi @solinyc http://stylifyme.com/ works again.

**Comment by solinyc** [comment]
I appreciate the update, thank you! @micmro
